"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var message = 'Welcome back!';
console.log(message);
var x = 10;
var y = 20;
var sum;
var title = "Codevolution";
var isBeginner = true;
var total = 0;
var Name = 'Daniel';
var sentece = "My name is ".concat(Name, " \nI am a beginner in Typescript");
console.log(sentece);
var n = null;
var u = undefined;
var list1 = [1, 2, 3];
var list2 = [1, 2, 3];
var person1 = ["Daniel", 19];
var Color;
(function (Color) {
    Color[Color["Red"] = 5] = "Red";
    Color[Color["Green"] = 6] = "Green";
    Color[Color["Blue"] = 7] = "Blue";
})(Color || (Color = {}));
;
var c = Color.Green;
console.log(c);
var randomValue = 10;
randomValue = true;
randomValue = 'Daniel';
var myVariable = 'Daniel';
myVariable.toUpperCase();
console.log(myVariable);
